title: Default Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          text:
            type: textarea
            size: huge
  sidebar:
    width: 1/3
    sections:No utility classes were detected in your source files. If this is unexpected, doubNo utility classes were detected in your source files. If this is unexpected, double-check the `content` option in your Tailwind CSS configurationle-check the `content` option in your Tailwind CSS configuration
      pages:
        type: pages
        template: default
      files:
        type: files

